server:
  port: 8082
  session-timeout: 60
  Name: test-name


#kafka相关配置
spring:
    kafka:     # 指定kafka 代理地址，可以多个
      bootstrap-servers: 10.201.5.103:9092
      consumer:   # 指定默认消费者group id
        group-id: myGroup
      template:    # 指定默认topic id
        default-topic: test
      listener:   # 指定listener 容器中的线程数，用于提高并发量
        concurrency: 5
      producer:  # 每次批量发送消息的数量
        batch-size: 1000

    thymeleaf:
      prefix: classpath:/templates/
    mvc.view.prefix: /
    mvc.view.suffix: .html
    mvc.static-path-pattern: /static/**